#!/bin/bash
# enable-web-hardening.sh — web-tier hardening + asset-delivery pass for the
# Apache front end. Idempotent; `--revert` removes it. Mirrors the B2
# enable-php-fpm.sh pattern: ship the script in the engine overlay, generate
# the apache conf at install time (the deb owns /opt/unetlab, not /etc/apache2).
#
# Security (the load-bearing reason this exists):
#   The Laravel store is RETIRED (item C6 of the store decommission) — fresh
#   installs never ship /opt/unetlab/html/store at all. This deny-block stays
#   as belt-and-braces: an upgraded box that still has the old store tree on
#   disk (from before the decommission) must never have ANY of it served —
#   not even /store/public/, which used to be the deliberately-exposed
#   document root. There is no longer a legitimate reason for anything under
#   /store/ to be reachable, so the match now denies ^/store(/|$) outright
#   (previously: allow /store/public/, deny the rest — /store/.env leaked
#   APP_KEY + DB creds when the whole html/ tree served as static files).
#   Also adds baseline response-security headers and (since 6.7.13) a
#   Content-Security-Policy: script-src 'self' — no inline script executes.
#   All inline blocks/handlers were externalized or converted to delegated
#   listeners (engine actions.js/functions.js, console pages, store blades,
#   react bundle data-pnet-* attrs); NO nonces needed. CSP_MODE=report emits
#   Content-Security-Policy-Report-Only instead (violations show in the
#   browser devtools console, nothing is blocked); CSP_MODE=off omits it.
#
# Performance (free now that B2 gave us mpm_event + php-fpm):
#   - HTTP/2 (h2): the topology page pulls ~40 separate <script> tags; h2
#     multiplexes them over one TLS connection. Needs a non-prefork MPM +
#     a non-mod_php SAPI, both true post-B2.
#   - Cache-Control on static asset types via mod_expires: the heavy vendored
#     JS (ace 648K, jsPlumb 596K, guacamole-common 524K, jquery, …) shipped
#     with NO Cache-Control, so every topology reload re-requested them.
#     STALENESS NOTE: engine assets are not content-hashed, so a deb upgrade
#     can leave a client on cached JS for up to ASSET_TTL. ETag/Last-Modified
#     still ride along (conditional revalidation after expiry), and TTL is
#     deliberately modest. Bump cautiously.
set -euo pipefail

CONF=/etc/apache2/conf-available/pnet-hardening.conf
HTML=/opt/unetlab/html
ASSET_TTL="${ASSET_TTL:-3600}"   # seconds; static asset Cache-Control max-age
CSP_MODE="${CSP_MODE:-enforce}"  # enforce | report (Report-Only header) | off

# One policy for the whole vhost (engine + store + consoles). Notes:
#   style-src 'unsafe-inline'  — inline style= is load-bearing (jsPlumb node
#                                positioning); style injection is not script
#                                execution, chasing it has no practical value.
#   connect-src wss:/ws:       — web console sockets (explicit schemes for
#                                UAs where 'self' doesn't cover ws upgrades).
#   worker-src blob:           — Ace editor spawns its syntax workers from
#                                blob: URLs.
#   img/font data:             — icon/font data URIs in vendored CSS.
CSP_POLICY="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' wss: ws:; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; form-action 'self'"

log() { echo "[web-hardening] $*"; }

case "$CSP_MODE" in enforce|report|off) ;; *)
    echo "ERROR: CSP_MODE must be enforce|report|off (got '$CSP_MODE')" >&2; exit 1;; esac

revert() {
    log "reverting web hardening"
    a2disconf pnet-hardening >/dev/null 2>&1 || true
    rm -f "$CONF"
    # leave http2/headers/expires modules enabled (harmless without the conf)
    systemctl reload apache2 2>/dev/null || systemctl restart apache2
    log "reverted"
    exit 0
}
[ "${1:-}" = "--revert" ] && revert

# 1) modules this conf depends on
a2enmod headers expires >/dev/null 2>&1 || true
# http2 only loads cleanly on a non-prefork MPM (B2 = mpm_event). Guard it so a
# pre-B2 / reverted-to-prefork box doesn't fail configtest.
if apache2ctl -M 2>/dev/null | grep -q mpm_prefork; then
    log "WARNING: mpm_prefork active — skipping HTTP/2 (needs mpm_event from B2)"
    H2=0
else
    a2enmod http2 >/dev/null 2>&1 && H2=1 || H2=0
fi

# 2) the hardening conf (server scope → applies to both :80 and :443 vhosts)
{
cat <<EOF
# pnet-hardening.conf — generated by enable-web-hardening.sh. Do not edit by
# hand; re-run the script (or its --revert) instead.

# ── Security ──────────────────────────────────────────────────────────────
# Laravel store is retired (fresh installs never ship html/store at all).
# Belt-and-braces for an upgraded box where the old store tree still exists
# on disk: deny EVERYTHING under /store/, full stop — no public/ exception.
<LocationMatch "^/store(/|\$)">
    Require all denied
</LocationMatch>

# Never serve a bare .env anywhere under the docroot.
<FilesMatch "^\.env">
    Require all denied
</FilesMatch>

# Directory listing off (the vhosts historically set Options Indexes).
<Directory "$HTML">
    Options -Indexes +FollowSymLinks
</Directory>

# Baseline response headers.
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    # HSTS only on the TLS vhost; harmless to omit on :80.
    <If "%{HTTPS} == 'on'">
        Header always set Strict-Transport-Security "max-age=31536000"
    </If>
EOF

case "$CSP_MODE" in
enforce)
cat <<EOF
    # Content-Security-Policy (CSP_MODE=enforce): no inline script executes.
    Header always set Content-Security-Policy "$CSP_POLICY"
EOF
    ;;
report)
cat <<EOF
    # CSP_MODE=report: report-only soak — violations land in the browser
    # devtools console; nothing is blocked. Flip to enforce when clean.
    Header always set Content-Security-Policy-Report-Only "$CSP_POLICY"
EOF
    ;;
off)
cat <<EOF
    # CSP_MODE=off: no Content-Security-Policy header.
EOF
    ;;
esac

cat <<EOF
</IfModule>

# ── Functional aliases ─────────────────────────────────────────────────────
# Export bundles + log files live under /opt/unetlab/data, OUTSIDE the
# DocumentRoot. apiExportLabs() returns a "/Exports/<file>.zip" URL (and the
# UIs link to it), but the shipped vhosts only granted the directory without
# aliasing the URL — so every export download 404'd. Map them here at server
# scope so both the :80 and :443 vhosts serve them.
Alias /Exports /opt/unetlab/data/Exports
Alias /Logs /opt/unetlab/data/Logs
<Directory "/opt/unetlab/data/Exports">
    Require all granted
    Options -Indexes
</Directory>
<Directory "/opt/unetlab/data/Logs">
    Require all granted
    Options -Indexes
</Directory>

# ── Performance ───────────────────────────────────────────────────────────
EOF

if [ "$H2" = 1 ]; then
cat <<EOF
# HTTP/2 (falls back to http/1.1 for old clients).
Protocols h2 http/1.1
EOF
fi

cat <<EOF
<IfModule mod_expires.c>
    ExpiresActive On
    <FilesMatch "\.(js|css|png|jpe?g|gif|svg|ico|woff2?|ttf|eot|map)\$">
        ExpiresDefault "access plus ${ASSET_TTL} seconds"
        Header append Cache-Control "public"
    </FilesMatch>
    # Content-hashed build output (islands: canvas-flow.Dr4Maef8.js, and any
    # other <name>.<hash>.<ext>) is IMMUTABLE by construction -- the hash IS the
    # version, so a changed file is a changed URL and can never go stale. It was
    # previously served with the same ${ASSET_TTL}s TTL as everything else, so
    # every repeat visit re-fetched the whole canvas bundle (648 kB for
    # canvas-flow alone).
    #
    # ORDER MATTERS AND IS DELIBERATE: this block must come AFTER the generic one.
    # Both FilesMatch blocks match a hashed .js/.css, Apache applies every match
    # in order, and the LAST one wins -- so the specific rule has to be last or
    # the generic 3600s ExpiresDefault silently overrides it. Header set (not
    # append) is likewise required, or the generic block's appended "public"
    # would be tacked onto this value.
    <FilesMatch "\.[A-Za-z0-9_-]{8,}\.(js|css)\$">
        ExpiresDefault "access plus 1 year"
        Header set Cache-Control "public, max-age=31536000, immutable"
    </FilesMatch>
</IfModule>

# Widen compression beyond the apache default to the asset types we actually
# ship (mod_deflate is already enabled; this just ensures coverage).
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml \\
        application/javascript application/x-javascript text/javascript \\
        application/json application/xml image/svg+xml
</IfModule>
EOF
} > "$CONF"

# 3) enable + validate before reload (never leave apache unable to start)
a2enconf pnet-hardening >/dev/null
if ! apache2ctl configtest >/dev/null 2>&1; then
    echo "ERROR: apache configtest failed with pnet-hardening.conf — reverting" >&2
    a2disconf pnet-hardening >/dev/null 2>&1 || true
    rm -f "$CONF"
    exit 1
fi
systemctl reload apache2 2>/dev/null || systemctl restart apache2

# 4) verify the security win actually holds (the whole point)
code=$(curl -sk -o /dev/null -w '%{http_code}' https://127.0.0.1/store/.env || echo 000)
case "$code" in
    403|404) log "OK — /store/.env blocked ($code)";;
    *) echo "ERROR: /store/.env still reachable (http $code)" >&2; exit 1;;
esac
# The store is retired — /login/ (engine-native login) is the thing that must
# serve now, and /store/ (in its entirety, no more public/ exception) must be
# denied even if the old tree still exists on an upgraded box.
login=$(curl -sk -o /dev/null -w '%{http_code}' https://127.0.0.1/login/ || echo 000)
case "$login" in
    200) log "OK — /login/ serves ($login); h2=$H2, asset_ttl=${ASSET_TTL}s";;
    *) echo "ERROR: /login/ broke (http $login)" >&2; exit 1;;
esac
store=$(curl -sk -o /dev/null -w '%{http_code}' https://127.0.0.1/store/ || echo 000)
case "$store" in
    403|404) log "OK — /store/ denied ($store)";;
    *) echo "ERROR: /store/ still reachable (http $store)" >&2; exit 1;;
esac
if [ "$CSP_MODE" != "off" ]; then
    [ "$CSP_MODE" = "enforce" ] && want='^content-security-policy:' \
                                || want='^content-security-policy-report-only:'
    if curl -skI https://127.0.0.1/ | tr -d '\r' | grep -qi "$want"; then
        log "OK — CSP header present (mode=$CSP_MODE)"
    else
        echo "ERROR: CSP header missing (mode=$CSP_MODE)" >&2; exit 1
    fi
fi
