#!/bin/bash
# pnet-satdeb-push.sh — push matching satellite + bridge debs to a joined
# satellite and restart satd. Runs as root in a transient systemd unit
# (pnet-satdeb-<job>, spawned by brokerd's cluster_sync_satellite):
#
#   pnet-satdeb-push.sh <sat_ip> <satellite_deb_path> <bridge_deb_path> <job>
#
# Transport: scp/ssh over the cluster Ed25519 key (same as image sync).
# Progress lands in html/cluster/jobs/<job>.json (same poll as image sync /
# cluster/api.php?action=sync_status).  The worker verifies both package
# identities and requires their Debian versions to match before any network
# copy. Final state: "done" or "error".
set -u
set -o pipefail

SAT="${1:-}"
SAT_DEB="${2:-}"
BRIDGE_DEB="${3:-}"
JOB="${4:-}"

BASE="/opt/unetlab/html/cluster"
ST="${BASE}/jobs/invalid.json"
KEY="/etc/pnetlab/cluster/id_ed25519"
SSHOPT="-i ${KEY} -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10"

mkdir -p "${BASE}/jobs"
upd() {
    # Escape any double-quotes in the message so the JSON stays valid.
    local msg="${3//\"/}"
    printf '{"state":"%s","pct":%s,"msg":"%s"}\n' "$1" "$2" "$msg" > "$ST"
    chmod 644 "$ST" 2>/dev/null || true
}
fail() { upd "error" 0 "$1"; exit 1; }

# ── arg validation ─────────────────────────────────────────────────────────────
[ "$#" -eq 4 ] && [ -n "$SAT" ] && [ -n "$SAT_DEB" ] && \
    [ -n "$BRIDGE_DEB" ] && [ -n "$JOB" ] || fail "bad arguments"
[[ "$JOB" =~ ^[0-9a-f]{16}$ ]] || fail "bad job id"
ST="${BASE}/jobs/${JOB}.json"
[ -f "$KEY" ] || fail "cluster key missing (/etc/pnetlab/cluster/id_ed25519)"
[ -f "$SAT_DEB" ] || fail "satellite deb not found: ${SAT_DEB}"
[ -f "$BRIDGE_DEB" ] || fail "bridge deb not found: ${BRIDGE_DEB}"

deb_field() {
    dpkg-deb -f "$1" "$2" 2>/dev/null || true
}

SAT_PACKAGE="$(deb_field "$SAT_DEB" Package)"
SAT_VERSION="$(deb_field "$SAT_DEB" Version)"
SAT_ARCH="$(deb_field "$SAT_DEB" Architecture)"
BRIDGE_PACKAGE="$(deb_field "$BRIDGE_DEB" Package)"
BRIDGE_VERSION="$(deb_field "$BRIDGE_DEB" Version)"
BRIDGE_ARCH="$(deb_field "$BRIDGE_DEB" Architecture)"
[ "$SAT_PACKAGE" = pnetlab-satellite ] || fail "satellite deb package identity is invalid"
[ "$SAT_ARCH" = amd64 ] || fail "satellite deb architecture is not amd64"
[ "$BRIDGE_PACKAGE" = pnetlab-bridge-dkms ] || fail "bridge deb package identity is invalid"
[ "$BRIDGE_ARCH" = all ] || [ "$BRIDGE_ARCH" = amd64 ] || \
    fail "bridge deb architecture is not all/amd64"
[ -n "$SAT_VERSION" ] && [ "$SAT_VERSION" = "$BRIDGE_VERSION" ] || \
    fail "satellite and bridge deb versions do not match"

# Package filenames are generated by dpkg and intentionally constrained before
# they are interpolated into a remote /tmp path. The source paths themselves
# are jailed by brokerd, but this worker is the authoritative root-side check.
SAT_NAME="$(basename -- "$SAT_DEB")"
BRIDGE_NAME="$(basename -- "$BRIDGE_DEB")"
case "$SAT_NAME" in pnetlab-satellite_*.deb) ;; *) fail "invalid satellite deb filename" ;; esac
case "$BRIDGE_NAME" in pnetlab-bridge-dkms_*.deb) ;; *) fail "invalid bridge deb filename" ;; esac

upd "running" 0 "connecting to ${SAT}"

# ── 1. scp both debs to the satellite (0 → 70 %) ───────────────────────────────
REMOTE_SAT_DEB="/tmp/${SAT_NAME}"
REMOTE_BRIDGE_DEB="/tmp/${BRIDGE_NAME}"
upd "running" 5 "copying satellite + bridge packages to ${SAT}"

SCP_ERR=$(scp -i "${KEY}" -o BatchMode=yes -o StrictHostKeyChecking=accept-new \
               -o ConnectTimeout=10 \
               "${SAT_DEB}" "${BRIDGE_DEB}" "root@${SAT}:/tmp/" 2>&1)
SCP_RC=$?
if [ "${SCP_RC}" -ne 0 ]; then
    # scp can leave the first payload behind when a multi-file transfer fails
    # part-way through.  The names are generated above from package filenames,
    # so this cleanup remains a fixed /tmp target on the satellite.
    ssh ${SSHOPT} "root@${SAT}" \
        "rm -f -- $(printf '%q' \"${REMOTE_SAT_DEB}\") $(printf '%q' \"${REMOTE_BRIDGE_DEB}\")" \
        >/dev/null 2>&1 || true
    # Sanitise newlines for the JSON msg field
    ERRMSG=$(printf '%s' "${SCP_ERR}" | tr '\n' ' ' | tr '"' "'")
    fail "scp failed (rc ${SCP_RC}): ${ERRMSG}"
fi

upd "running" 70 "installing satellite + pnetlab-bridge-dkms on ${SAT}"

# ── 2. dpkg -i on the satellite (70 → 90 %) ───────────────────────────────────
# Always remove the temporary payloads, including after a failed dpkg. A
# package transaction is still atomic at the dpkg database level, while the
# two files cannot linger as an accidental root-readable staging area.
# After dpkg succeeds, require both package records and the bridge's runtime
# check/status entry points before reporting the job complete.
remote_install="set +e; DEBIAN_FRONTEND=noninteractive dpkg -i $(printf '%q' "$REMOTE_SAT_DEB") $(printf '%q' "$REMOTE_BRIDGE_DEB"); rc=\$?; if [ \$rc -eq 0 ]; then dpkg-query -W pnetlab-satellite pnetlab-bridge-dkms >/dev/null 2>&1 || rc=1; test -x /usr/lib/pnetlab/pnetlab-bridge-lacp-check || rc=1; test -x /usr/sbin/pnetlab-bridge-dkms-status || rc=1; fi; rm -f -- $(printf '%q' "$REMOTE_SAT_DEB") $(printf '%q' "$REMOTE_BRIDGE_DEB"); exit \$rc"
DPKG_ERR=$(ssh ${SSHOPT} "root@${SAT}" \
    "$remote_install" 2>&1)
DPKG_RC=$?
if [ "${DPKG_RC}" -ne 0 ]; then
    ERRMSG=$(printf '%s' "${DPKG_ERR}" | tr '\n' ' ' | tr '"' "'")
    fail "dpkg -i failed (rc ${DPKG_RC}): ${ERRMSG}"
fi

upd "running" 90 "restarting pnetlab-satd on ${SAT}"

# ── 3. restart satd (90 → 100 %) ─────────────────────────────────────────────
# The satd restart drops the SSH session (expected); treat that rc as success.
ssh ${SSHOPT} -o ServerAliveInterval=5 -o ServerAliveCountMax=2 \
    "root@${SAT}" "systemctl restart pnetlab-satd" 2>&1 || true

upd "done" 100 "satellite ${SAT} and LACP bridge updated; satd restarted"
exit 0
